#!/usr/bin/env escript
%% -*- erlang -*-

main([]) -> build(compile);
main([Task|Tasks]) -> build(list_to_atom(Task)), main(Tasks).

build(clean) ->
    [file:delete(X) || X <- filelib:wildcard(filename:join("ebin","*"))],
    file:del_dir("ebin");

build(compile) ->
    file:build_dir("ebin"),
    [case lfe_comp:file(X,[report,{outdir,"ebin"}]) of
         error -> halt(1);
         {ok,_} -> ok
     end || X <- filelib:wildcard(filename:join("src","*.lfe"))];

build(X) -> io:format("~s ?!~n",[X]).
